FROM ubuntu:16.04

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install python and pip
RUN apt-get update && apt-get -y install python3 python3-pip

# add app
COPY . /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip3 install -r requirements.txt

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

EXPOSE 5000
# run server
CMD python3 run.py run --host=0.0.0.0
