name: Comment

on: 
  repository_dispatch:
    types: [deploy-command]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Output command and arguments
        run: |
          echo ${{ github.event.client_payload.slash_command.command }}
          echo ${{ github.event.client_payload.slash_command.args }}
          echo ${{ github.event.client_payload.slash_command.arg1 }}
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload.slash_command) }}
        run: echo "$PAYLOAD_CONTEXT"
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          body: |
            **Deploying release:** ${{ github.event.client_payload.slash_command.release }}
